### ISSUE TITLE
Add option to whitelist setUp and tearDown methods.

### ISSUE THREAD

**Issue by proofit404** [adamchainz/pytest-super-check#120]
Hi, thanks for the awesome project.

Let's imagine we have a regular Django project.

`setUp` and `tearDown` methods can freely omit the `super` call because Django has `_pre_setup` and `_post_teardown` methods instead.

But we want to be sure every `setUpClass` method still calls `super`.

What do you think?

Have a good day.

Best regards,
Artem.

**Comment by adamchainz** [comment]
Hi,

I built this for a large Django project where the "you can omit `super`" behaviour was what caused the problems.

Some test cases inherited from Django's `TestCase` (or our project's thin wrapper) which meant omitting `super` was fine. But others inherited from a subclass in our project that used `setUp` etc. to add extra data or assertion behaviour, and omitting `super` there could lead to hard-to-debug errors.

Because this was built to "fix" the complacency Django allows in calling `super`, I don't want to add any rule in to again allow it.

Thanks,

Adam

**Comment by proofit404** [comment]
Makes sense. Thanks!
